import os
import unittest
WORK_DIR = os.path.dirname(__file__)
os.chdir(WORK_DIR)
from sentsformal import SentsFormal

class TestAPI(unittest.TestCase):
    def setUp(self):
        self.sf = SentsFormal('./prompts/arithmetic.txt')

    def tearDown(self):
        pass
    
    def test_01_equation(self):
        formal = self.sf.formalize(
            sentence='The friction force generated by the goods during braking is less than 0.5 N.',
            given_trans={"friction force": "Fm"}
        )
        print(formal)
        self.assertEqual(formal, 'Fm < 0.5')



if __name__ == '__main__':
    # 测试用例执行顺序，按函数名字典序
    unittest.main()
