import os, requests, json, re
from llm_base.ollama_call import OllamaCall
from llm_base.chat_server_call import ChatServerCall

class SentsFormal:
    def __init__(self, prompt_temp_path='arithmetic.txt'):
        self.prompt_temp_path = prompt_temp_path
        self.url = 'http://47.254.92.46:8000/openai/'
        with open('./sents_formal_llm/formal_data.json', 'r', encoding='utf-8') as f:
            self.buffer_formal = json.load(f)

    def formalize(self, sentence, given_trans={}, num_tries=1, temperature=0.2):
        # 先查缓存
        sentence = sentence.strip()
        if sentence in self.buffer_formal:
            return [self.buffer_formal[sentence]], []
        
        # 调用LLM
        with open(self.prompt_temp_path, 'r', encoding='utf-8') as f:
            prompt = f.read()
            prompt = prompt.replace('<A_NEW_NATURAL_LANGUAGE_SENTENCE_TO_BE_TRANSLATED>', sentence)
            prompt = prompt.replace('<A_DICTIONARY_OF_SUB-TRANSLATIONS>', json.dumps(given_trans))

        # 尝试3次
        for i in range(3):
            print('try:', i)
            ret = self.chat(prompt, num_tries, temperature)
            if ret['status'] != 'OK':
                continue

            list_result, sub_trans_stats_result = self.parse_output_choices(ret['output_choices'])
            if len(list_result) == 0:
                continue
            return list_result, sub_trans_stats_result

        return [], []
    
    def parse_output_choices(self, output_choices):
        list_sub_trans = []
        list_result = []
        for choice in output_choices:
            try:
                exp_dict, trans_ret = self.parse_choice(choice)
                list_result.append(trans_ret)
                list_sub_trans += exp_dict.items()
            except:
                print('Parse Fail.')

        # 统计子翻译占比
        stats_result = self.stats_sub_trans(list_sub_trans, len(output_choices))
        return list_result, stats_result
    
    def stats_sub_trans(self, list_sub_trans, max_count):
        stats_result = [] # nl, formal, rate
        for sub_trans in set(list_sub_trans):
            have_count = list_sub_trans.count(sub_trans)
            rate = round(have_count / max_count, 2)
            stats_result.append({'nl': sub_trans[0], 'formal': sub_trans[1], 'rate': rate})
        return stats_result

    def parse_choice(self, choice):
        exp_dict, trans_ret = {}, ''
        exp_dict_str = self.find_center(choice, left='Explanation dictionary:', right='So the final constraint translation is:')
        if exp_dict_str:
            try:
                exp_dict = json.loads(exp_dict_str)
            except:
                print(f'Warning: JSON {exp_dict_str} fails to parse.')

        if 'FINISH' not in choice:
            choice += 'FINISH'
        trans_ret = self.find_center(choice, left='So the final constraint translation is:', right='FINISH')
        trans_ret = trans_ret.strip().rstrip('.')

        return exp_dict, trans_ret

    def find_center(self, total, left, right):
        total = total.replace('\n', ' ')
        pattern = re.escape(left) + "(.*?)" + re.escape(right)
        center = re.findall(pattern, total)
        if len(center) > 0:
            return center[0]
        else:
            return None
            
    def chat(self, input_prompt, num_tries, temperature, chat_session_id=None):
        print('input_prompt:', input_prompt)
        
        # 使用代理模型服务
        # ret = ChatServerCall().chat_server(input_prompt, num_tries, temperature, model, chat_session_id)
        # 使用本地模型
        ret = OllamaCall().chat_ollama(input_prompt, temperature)
        return ret
    
if __name__ == '__main__':
    sf = SentsFormal()
    exp_dict, trans_ret = sf.parse_choice('"The friction force generated by the goods during braking" from the input translates to the variable Fm. "is less than" from the input translates to the operator <. "0.5 N" translates to a number 0.5.\nExplanation dictionary: {"friction force" : "Fm", "is less than" : "<", "0.5 N" : "0.5"}\nSo the final constraint translation is: Fm < 0.5.FINISH')
    print(exp_dict, trans_ret)
