import os
import unittest
WORK_DIR = os.path.dirname(__file__)
os.chdir(WORK_DIR)
from sents_similarity import SentsSimilarity

class TestAPI(unittest.TestCase):
    def setUp(self):
        self.ss = SentsSimilarity('./prompts/two_sentences.txt')

    def tearDown(self):
        pass
    
    def test_01_compare(self):
        similarity = self.ss.compare(
            sentence1='The friction force generated by the goods during braking is less than 0.5 N.',
            sentence2='The automatic guided vehicle can stop safely when encountering obstacles'
        )
        print(similarity)
        # self.assertEqual(similarity, 'Fm < 0.5')
        



if __name__ == '__main__':
    # 测试用例执行顺序，按函数名字典序
    unittest.main()
