import os, requests, json, re

class SentsSimilarity:
    def __init__(self, prompt_temp_path='two_sentences.txt'):
        self.prompt_temp_path = prompt_temp_path
        self.url = 'http://47.254.92.46:8000/openai/'
        # with open('./sents_formal_llm/formal_data.json', 'r', encoding='utf-8') as f:
        #     self.buffer_formal = json.load(f)

    def compare(self, sentence1, sentence2, num_tries=1, temperature=0.2):
        # 先查缓存
        # sentence = sentence.strip()
        # if sentence in self.buffer_formal:
        #     return [self.buffer_formal[sentence]], []
        
        # 调用LLM
        with open(self.prompt_temp_path, 'r', encoding='utf-8') as f:
            prompt = f.read()
            prompt = prompt.replace('<SENTENCE_1>', sentence1)
            prompt = prompt.replace('<SENTENCE_2>', sentence2)

        ret = self.chat(prompt, num_tries, temperature)
        if ret['status'] == 'OK':
            list_result = self.parse_output_choices(ret['output_choices'])
            return list_result
        else:
            return []
    
    def parse_output_choices(self, output_choices):
        list_result = []
        for choice in output_choices:
            try:
                similarity = self.parse_choice(choice)
                if similarity != None:
                    list_result.append(similarity)
                else:
                    print('Content error.')
            except:
                print('Parse Fail.')

        return list_result

    def parse_choice(self, choice):

        similarity_str = self.find_center(choice, left='{"similarity": ', right='}')
        if similarity_str:
            return int(similarity_str)
        else:
            return None

    def find_center(self, total, left, right):
        total = total.replace('\n', ' ')
        pattern = re.escape(left) + "(.*?)" + re.escape(right)
        center = re.findall(pattern, total)
        if len(center) > 0:
            return center[0]
        else:
            return None

    def chat(self, input_prompt, num_tries, temperature, chat_session_id=None):
        print('input_prompt:', input_prompt)
        
        param = {
            "input_prompt": input_prompt,
            "temperature": temperature,
            "num_tries": num_tries,
            "model": "gpt-3.5-turbo"
        }
        if chat_session_id:
            param['chat_session_id'] = chat_session_id

        r = requests.post(url=self.url, json=param)
        return r.json()
    
if __name__ == '__main__':
    pass
    # sf = SentsFormal()
    # exp_dict, trans_ret = sf.parse_choice('"The friction force generated by the goods during braking" from the input translates to the variable Fm. "is less than" from the input translates to the operator <. "0.5 N" translates to a number 0.5.\nExplanation dictionary: {"friction force" : "Fm", "is less than" : "<", "0.5 N" : "0.5"}\nSo the final constraint translation is: Fm < 0.5.FINISH')
    # print(exp_dict, trans_ret)
